version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm install
  pre_build:
    commands:
      - echo "Cleaning up previous builds..."
      - rm -rf package.zip lambda.zip || true
  build:
    commands:
      - echo "Zipping Lambda function..."
      - zip -r lambda.zip index.js node_modules
  post_build:
    commands:
      - echo "Build completed. lambda.zip is ready."

artifacts:
  files:
    - lambda.zip
  discard-paths: yes