version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm install

  pre_build:
    commands:
      - echo "Cleaning up old artifacts..."
      - rm -f lambda.zip || true

  build:
    commands:
      - echo "Zipping Lambda function..."
      - zip -r lambda.zip index.js node_modules
      - echo "Build complete."

  post_build:
    commands:
      - echo "Verifying zip contents..."
      - unzip -l lambda.zip
      - echo "Build process finished."

artifacts:
  files:
    - lambda.zip
  discard-paths: yes